name: Bump Version and Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Type of release (major, minor, patch)"
        required: true
        default: "patch"

jobs:
  version-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.RELEASE_PAT }}

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "1.x"

      - name: Increase Version
        run: deno task version:increase ${{ github.event.inputs.releaseType }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Latest Version
        run: echo "LATEST_VERSION=$(deno task version:latest)" >> $GITHUB_ENV

      - name: Commit and Push Version Update
        run: |
          git config --local user.email "reed+github@vonredwitz.com"
          git config --local user.name "Reed von Redwitz"
          git add src/versions.json
          git commit -m "increase version: ${{ env.LATEST_VERSION }}"
          git tag -a "${{ env.LATEST_VERSION }}" -m "create version ${{ env.LATEST_VERSION }}"
          git push origin HEAD:main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
        with:
          tag_name: ${{ env.LATEST_VERSION }}
          release_name: ${{ env.LATEST_VERSION }}
          body: ""
          draft: true
          prerelease: false
